baseurl = "https://introduction.com/"
builddrafts = false
canonifyurls = true
enforce_ssl = false
languageCode = "en-us"
theme = "spx-theme"
title = "My New Hugo Site"
[[menu.main]]
identifier = "slots"
name = "slots"
url = "/games/slots/"
weight = 2
[[menu.main]]
identifier = "news"
name = "News"
url = "/"
weight = 5
[[menu.main]]
identifier = "jackpots"
name = "jackpots"
url = "/games/jackpots/"
weight = 4
[[menu.main]]
identifier = "live"
name = "live"
url = "/games/live/"
weight = 3
[[menu.main]]
identifier = "games"
name = "games"
url = "/games/"
weight = 1
[params]
avatar = "img/profile.jpg"
bloghead = "Blog"
cachebuster = false
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
description = "Website Description"
email = "youremail@email.com"
fadein = true
faviconfile = "img/fav.ico"
firstname = "Introduction"
footertext = ""
highlightjs = true
introheight = "large"
localtime = true
placeholderimg = "/img/workday.jpg"
projectcolumns = "3"
sharebuttons = true
sharefacebook = true
sharegoogleplus = true
sharepinterest = false
sharetwitter = true
showallposts = false
showblog = true
showlatest = true
showprojects = true
tagline = "I'm a theme for Hugo."
theme = "dark"
timezone = "America/Los_Angeles"
[[params.social]]
icon = "twitter"
url = "https://twitter.com/"
[[params.social]]
icon = "facebook"
url = "https://facebook.com/"
[[params.social]]
icon = "linkedin"
url = "https://linkedin.com/"
